# Generated by Django 4.1 on 2024-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("question_text", models.CharField(max_length=50)),
                ("answer_text", models.CharField(max_length=50)),
            ],
        ),
    ]
