# Generated by Django 4.1 on 2024-05-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testwise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewquestion",
            name="department_name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="interviewquestion",
            name="answer_text",
            field=models.TextField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="interviewquestion",
            name="question_text",
            field=models.TextField(default="", max_length=50),
        ),
    ]
