# Generated by Django 4.1 on 2024-05-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testwise", "0002_interviewquestion_department_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentInfo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("department_name", models.CharField(default="", max_length=30)),
                ("compulsory_courses", models.TextField(default="", max_length=150)),
                (
                    "graduation_requirements",
                    models.TextField(default="", max_length=150),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="interviewquestion",
            name="answer_text",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="interviewquestion",
            name="question_text",
            field=models.TextField(default="", max_length=100),
        ),
    ]
